spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/notes
      driver-class-name: org.postgresql.Driver
      username: myuser
      password: mypassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      id:
        uuid_generator: uuid-ossp
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
        use_sql_comments: true
