spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/notes
      driver-class-name: org.postgresql.Driver
      username: myuser
      password: mypassword
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        show_sql: true
        format_sql: true
        use_sql_comments: false
        javax:
          cache:
            missing_cache_strategy: create
        cache:
          use_second_level_cache: true
          use_query_cache: true

    open-in-view: false

logging:
  level:
    org.hibernate: debug
