services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: notes
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - local

  app:
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8090:8080"
    networks:
      - local
    depends_on:
      - db

volumes:
  postgres-data:

networks:
  local:
    driver: bridge
